export default {
    generator: [
        { name: 'Project', path: '/project' },
        { name: 'Entity', path: '/entity' },
        { name: 'Layer', path: '/layer' },
        { name: 'Artisan', path: '/artisan' },
        { name: 'Preset', path: '/preset' },
    ],
    oapi: [
        { name: 'OpenAPI', path: '/oapi' },
        { name: 'Preset', path: '/preset' },
        { name: 'Example', path: '/example' },
        { name: 'Header', path: '/header' },
        { name: 'Parameter', path: '/parameter' },
        { name: 'Request', path: '/request' },
        { name: 'Response', path: '/response' },
        { name: 'Schema', path: '/schema' },
        { name: 'Security', path: '/security' },
        { name: 'Requirement', path: '/requirement' },
        { name: 'Server', path: '/server' },
        { name: 'Tag', path: '/tag' },
        { name: 'Path', path: '/path' },
    ],
    entity: ['Cast', 'Data', 'Faker', 'Field', 'File', 'Index', 'Property', 'Relation', 'Validation'],
}
